travis:
  secure:
    BINSTAR_TOKEN: oYxCvq+OfQ14FqdByErRHdZcK7LtTydHpCXaAZ/FuNocPB5aTmfXlZY7QIgbrtdXOX7or++ynZPGPZwAfFI36WajfO/vlPphGU8SaWEi4RRDHuNE6Icsvb8f1+DcVdmp2lvmZe/bFuigmGNMQMsjU63RHpa5w7a9ftD+et4VaSajHNeU1RbwoxkarRD2ErOpKtU3o9cK+Bkb00ckj+nvHbK+BkCC1qg4zYGhvwcC5LEJqWFHRDm7qajC6YKn2Yjo0YEETSqxnSWDjf5RxYVpaDKfkxkkpWFDMaRQ19xD4BgpS4zUAOxf17Gtm45zIlriheybxX/aKYG5+yKpf6bJRqwDgFEkBFO5JvIILOsrRVueJWsxnR8dgQdISKu2YPlHjAspYyTrFWeofEF/4BEuhM710qMlqZtTlFRyfrDi9HRWYVAlWzTQE6xGJ5/W8om0xFBHab+uKt1coKbMWcm+QIZ4+5hH6kuZ2WCgG8Y1RrtAjetdlLnwfqiAa723HpvIjp0WqRIRVReCAYINfOHT2P93SxM/U6TmHzMGFIg9M+B6NOxIIqmvqVFpHK7a6EHPjwlA5wuuLZ8fHtaYtqOn4Lf2AKgKgPCpjYsMovL82R9cQi8ymA49cjtpoEFZ9yV7pfQtDpAOV6drgm2pDkBojrI+YPxUiaGYvvGswiyfyzg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
